### ISSUE TITLE
Enforce cost limits on use

### ISSUE THREAD

**Issue by Alium58** [loathers/bountiful#7]
Currently script enforces cost limits when buying zone unlockers and banish items. I believe this should also be enforced on item use. What do others think?

**Comment by docrostov** [comment]
100% agreed. from a philosophical perspective, people who are using this script are more likely to be newbies and more likely to be much less able to comfortably afford to spend, say, 150,000 meat by buying an expensive banish 3x a day. it is more likely to make them sad and quit the game because they get into a rut.

**Comment by Alium58** [comment]
Good deal glad we agree. 

For content unlockers we can print a message telling the user which unlocker to manually use if they want the bounty.

For banishers we could print that it was skipped for being too expensive if we have one on hand. Seems like it could get spammy though as it could get printed multiple times per combat. Might be something we try and refine

**Comment by Trumeg** [comment]
The idea I came up with is to get the script to check prices before it looks for banishes and have it ignore items above the price limit.
I am not sure how to make that happen. I don't see how the maxBanish value is being used. I think the price check has to occur before it does this though. Does this idea have merit or am I going in the wrong direction?
